In [1]:
import tensorflow as tf

In [2]:
print("TensorFlow version:{}",format(tf.__version__))

TensorFlow version:{} 2.18.0


In [5]:
d0=tf.constant (1)
print("Dimension is", tf.rank(de).numpy ())
print(d0)

Dimension is 0
tf.Tensor(1, shape=(), dtype=int32)


**n=1:vector**

In [8]:
d1=tf.ones((2,))
print("Dimension is", tf.rank(d1).numpy ())
print(d1)

Dimension is 1
tf.Tensor([1. 1.], shape=(2,), dtype=float32)


**n=2 : Matrix**

In [9]:
d2=tf.ones((2,2))
print("Dimension is", tf.rank(d2).numpy ())
print(d2)

Dimension is 2
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


**n=3: multidimensional or 3d**

In [10]:
d3=tf.ones((2,2,2))
print("Dimension is", tf.rank(d3).numpy ())
print(d3)

Dimension is 3
tf.Tensor(
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]], shape=(2, 2, 2), dtype=float32)


In [13]:
x1=tf.Variable(23)
x2=tf.Variable([[[0.,1.,2.],[3.,4.,5.]],[[6.,7.,8.],[9.,10.,11.]]])
x0=123
x1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=23>

***constant and assign***

In [14]:
x1.assign(100)
x1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=100>

In [16]:
x1=tf.constant(100)
print(x1)
x1.assign(200)
x1

tf.Tensor(100, shape=(), dtype=int32)


AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [17]:
x2

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]], dtype=float32)>

In [18]:
x0

123

Reshape

In [19]:
x112=tf.reshape(x2,[1,12])
x112

<tf.Tensor: shape=(1, 12), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]],
      dtype=float32)>

declaring variable with type

In [20]:
xf64=tf.Variable(202,dtype=tf.float64)
xf64

<tf.Variable 'Variable:0' shape=() dtype=float64, numpy=202.0>

In [21]:
tf.rank(xf64)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [22]:
tf.rank(x2)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [26]:
t=tf.constant([[[1,1,1],[2,2,2]],[[4,3,5],[4,4,414]]])
tf.rank(t).numpy()

np.int32(3)

In [27]:
t.numpy()

array([[[  1,   1,   1],
        [  2,   2,   2]],

       [[  4,   3,   5],
        [  4,   4, 414]]], dtype=int32)

tensor slicing

In [28]:
tensor3=t[1,1,2]
tensor3

<tf.Tensor: shape=(), dtype=int32, numpy=414>

In [31]:
x=tf.constant ([0,1,1,2,3,4,8,13,21,34])
print ("Before 4:", x[:4].numpy())
print ("After 4:",x[4:].numpy())
print("From 2, before 7:", x[2:7].numpy())
print ("Every other item:", x[::2].numpy())
print ("Reversed:", x[:: -1].numpy())

Before 4: [0 1 1 2]
After 4: [ 3  4  8 13 21 34]
From 2, before 7: [1 2 3 4 8]
Every other item: [ 0  1  3  8 21]
Reversed: [34 21 13  8  4  3  2  1  1  0]


In [32]:
a=tf.constant([[1,2],[3,4]])
i=tf.cast(a,tf.int32)
print(a)
print(i)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
